travis:
  secure:
    BINSTAR_TOKEN: NuR+pgwlaDe1QXM1r64DFOqbw/l2hJZULNH1PAsB5HquMBSd4PMGpQKrmzhk7w30v401aAMGinPLAU6gJ7pHpLcETmHW2xjdx+ynowjxTbXhGxTvWqC78vrEld2LodNTFgijI/yL3H4DlmPx6sb0oLZn8RD3oibc9Yym8HyzxGPgTF20rUJhqRM1FEf5jY0HfM5+sOvWUSS0EwligUucW+yHrpNwgLZngdasKn1fYDwY9KH41FHAqJk2MYj+4QYXmnFPlUTKKByOGqOTzdl2Xfki/zeLl3ASqRassXryHImBpTfnD+BaDoozDY23xw2z0ncZq8kUoP/IGpoY3ruan4I8Cs4Nw5QM4DP+C4BAWkShlG4KhwntAXoLc91Vx4A774MqCOc3GcGXT7gecjRL5FZd+mk9Sk4aVKj13xhClOO8GrPO2j7UIjUnlZ41yEkmyxngOCm5sTgr4TIOpFR8PaU+DHz4xOctme200VrVsUPboMcV1V83GMFKeGoFa0nqkZkJCufL11JjOkGPzxhgduqgGE6AWukHaRCdLw5fx8k1bU/TQH6Cksqpok8UbRChA9NRyv9S5zAUnAtcH0j19v+JNic1af/kIiOwNvG6H2bKmlANB3ruCjHImGrbo9pHUzU9ioZWsUYyNURHsTaTub62LWYMiEHDkajWzH0p+P4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
