travis:
  secure:
    BINSTAR_TOKEN: iVaRu+0s6olWCeajNfxRvIRmT/hjymagX7t4JT2KeuSVMCROeoWcONNQZ/QBIffOQCu990FWB0lOz9iFeQav3jWXmWIiB5N4j83vA194Yh/p9ejBiSYvcyCMPPVvkUAr7I5pJpsGAOfCUqrKd3BrtcvbmUXwB3AgDVD46tR9N6vKTOK0q0DYd9XsimSlu0aM3OFJKeDKRf0x9ufFsXPlUI3SBWsy/wXZw5CjG7UdAjsDSS6ZyKBLZtnMyVLmViHY6c/Y0/og7RCo2u6eBniZNAsw2Jiv49l8Xi51uqpnLgwAxjheiJ1lQ0pVdy1sjr4DiXeSwu0zy0R4SCig8nMsLPEj59EgPeCuF8WcTbpBpq/+T58upZquOVYX+4/WHqtiBxhrjvSVLVGvqvgNoQbcpZNfbjkNbbh4dqcgwJ+TiX28yrpfp291m+BnOXkPj0ePHP/zmkGhUK21NJPbKD0y7Fsz74Jht8lTwDYPmFRuQJ3XzBTHfIFvEOyhl9trkynMyx2D0Tvhncv2tuynawXTsRQ5AZCZ2VTI8jVvOyUArwZqPuSSiDokiYRJf1VzbC0P/KyFVHmzO/5bJelgUsyJ5gflIkcuYn+j6lQLgtEgs2P7v4zMGgJu1TsYxCoM9Crb0bOPG0ccyu6vGCIiMCjLjZoUk27UtaNeuV0J3ixnqwY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
